export const runwayPaths: { [key: string]: any } = {
  ZSSS18R: require("../../../../assets/runways/ZSSS18R.png"),
  ZSSS18R_glide: require("../../../../assets/runways/ZSSS18R-Slide.png"),
  ZSSS36R: require("../../../../assets/runways/ZSSS36R.png"),
  ZSSS36R_glide: require("../../../../assets/runways/ZSSS36R-Slide.png"),
  ZSSS18L: require("../../../../assets/runways/ZSSS18L.png"),
  ZSSS18L_glide: require("../../../../assets/runways/ZSSS18L-Slide.png"),
  ZSSS36L: require("../../../../assets/runways/ZSSS36L.png"),
  ZSSS36L_glide: require("../../../../assets/runways/ZSSS36L-Slide.png"),
  ZLXY05L: require("../../../../assets/runways/ZLXY05L.png"),
  ZLXY05L_glide: require("../../../../assets/runways/ZLXY05L-Slide.png"),
  ZLXY05R: require("../../../../assets/runways/ZLXY05R.png"),
  ZLXY05R_glide: require("../../../../assets/runways/ZLXY05R-Slide.png"),
  ZLXY23L: require("../../../../assets/runways/ZLXY23L.png"),
  ZLXY23L_glide: require("../../../../assets/runways/ZLXY23L-Slide.png"),
  ZLXY23R: require("../../../../assets/runways/ZLXY23R.png"),
  ZLXY23R_glide: require("../../../../assets/runways/ZLXY23R-Slide.png"),
  ZYTL10: require("../../../../assets/runways/ZYTL10.png"),
  ZYTL10_glide: require("../../../../assets/runways/ZYTL10-Slide.png"),
  ZYTL28: require("../../../../assets/runways/ZYTL28.png"),
  ZYTL28_glide: require("../../../../assets/runways/ZYTL28-Slide.png"),
};
